apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/aws-samples/eks-workshop-v2/manifests/base-application/carts?ref=stable
  - service.yaml
  - gateway.yaml
  - httproute.yaml
patches:
  - path: service.yaml
  - path: gateway.yaml
  - path: httproute.yaml
