apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/aws-samples/eks-workshop-v2/manifests/base-application/carts?ref=stable
  - overlays/vpc-lattice/httproute.yaml

patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: carts
    spec:
      template:
        metadata:
          annotations:
            vpc-lattices-svcs.amazonaws.com/agent-inject: "true"
        spec:
          initContainers:
          - name: iptables-init
            securityContext:
              capabilities:
                add: ["NET_ADMIN"]
              privileged: true
            command:
            - /bin/sh
            - -c
            - |
              iptables -t nat -N EGRESS_PROXY
              iptables -t nat -A OUTPUT -p tcp -d 169.254.171.0/24 -j EGRESS_PROXY
              iptables -t nat -A EGRESS_PROXY -m owner --gid-owner 0 -j RETURN
              iptables -t nat -A EGRESS_PROXY -p tcp -j REDIRECT --to-ports 15000
          containers:
          - name: envoy-sigv4
            env:
            - name: ENVOY_PORT
              value: "15000"
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_DEFAULT_REGION
              value: us-west-2
            ports:
            - containerPort: 15000
          - name: carts
            env:
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_DEFAULT_REGION
              value: us-west-2
  target:
    kind: Deployment
    name: carts
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: carts
      annotations:
        networking.amazonaws.com/vpc-lattice-service: "true"
  target:
    kind: Service
    name: carts
