apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carts

resources:
  - https://github.com/aws-samples/eks-workshop-v2/manifests/base-application/carts?ref=stable
  - overlays/vpc-lattice/httproute.yaml

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: carts
        annotations:
          networking.amazonaws.com/vpc-lattice-service: "true"
      spec:
        ports:
          - port: 80
            targetPort: 8080
            protocol: TCP
            name: http
