apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carts

resources:
- https://github.com/aws-samples/eks-workshop-v2/manifests/base-application/carts?ref=stable
- overlays/vpc-lattice/httproute.yaml

patches:
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: carts
      annotations:
    application-networking.k8s.aws/target-group-attributes: |
      {"health_check_enabled":true,"health_check_port":8080,"health_check_protocol":"HTTP","health_check_path":"/actuator/health/liveness","health_check_interval_seconds":30,"health_check_timeout_seconds":5,"healthy_threshold_count":5,"unhealthy_threshold_count":2}
    application-networking.k8s.aws/enabled: "true"
  target:
    kind: Service
    name: carts
