apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/aws-samples/eks-workshop-v2/manifests/base-application/carts?ref=stable
  - overlays/vpc-lattice/httproute.yaml

patches:
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: carts
      annotations:
        networking.amazonaws.com/vpc-lattice-service: "true"
  target:
    kind: Service
    name: carts
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: carts
    spec:
      template:
        metadata:
          annotations:
            vpc-lattices-svcs.amazonaws.com/agent-inject: "true"
        spec:
          containers:
          - name: envoy-sigv4
            env:
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_DEFAULT_REGION
              value: us-west-2
          - name: carts
            env:
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_DEFAULT_REGION
              value: us-west-2
  target:
    kind: Deployment
    name: carts
