apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carts

resources:
- https://github.com/aws-samples/eks-workshop-v2/manifests/base-application/carts?ref=stable
- overlays/vpc-lattice/httproute.yaml

patches:
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: carts
      annotations:
        networking.amazonaws.com/vpc-lattice-service: "true"
        networking.amazonaws.com/vpc-lattice-health-check-port: "8080"
        networking.amazonaws.com/vpc-lattice-health-check-protocol: "HTTP"
        networking.amazonaws.com/vpc-lattice-health-check-path: "/actuator/health/liveness"
        networking.amazonaws.com/vpc-lattice-health-check-healthy-threshold: "5"
        networking.amazonaws.com/vpc-lattice-health-check-unhealthy-threshold: "2"
        networking.amazonaws.com/vpc-lattice-health-check-timeout: "5"
        networking.amazonaws.com/vpc-lattice-health-check-interval: "30"
  target:
    kind: Service
    name: carts
