apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  template:
    metadata:
      annotations:
        eks.amazonaws.com/pod-identity-init: "true"
        eks.amazonaws.com/role-arn: "arn:aws:iam::240484791744:role/ui-vpclattice-role"
    spec:
      containers:
      - name: ui
        env:
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: "regional"
        - name: AWS_DEFAULT_REGION
          value: "us-west-2"
        - name: AWS_SDK_LOAD_CONFIG
          value: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui
data:
  ENDPOINTS_CARTS: https://carts-service-0ba278018a6cba4d2.7d67968.vpc-lattice-svcs.us-west-2.on.aws
