apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
spec:
  template:
    metadata:
      annotations:
        vpc-lattices-svcs.amazonaws.com/agent-inject: "true"
    spec:
      containers:
      - name: carts
        env:
        - name: AWS_REGION
          value: us-west-2
