apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: carts-gateway
  namespace: carts
spec:
  gatewayClassName: vpc-lattice
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
