apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: carts-route
  namespace: carts
spec:
  parentRefs:
  - name: carts-gateway
    namespace: carts
  rules:
  - backendRefs:
    - name: carts
      port: 80
      weight: 1
