apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: carts
  namespace: carts
spec:
  hostnames:
  - carts.myorg.com
  parentRefs:
  - kind: Gateway
    name: lattice-gateway
    namespace: lattice-gateway
    sectionName: http-listener
  rules:
  - backendRefs:
    - name: carts
      kind: Service
      port: 80
      healthCheck:
        port: 8080
        path: /actuator/health/liveness
    matches:
    - path:
        type: PathPrefix
        value: /
