apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: carts
  namespace: carts
spec:
  hostnames:
  - carts.myorg.com
  parentRefs:
  - kind: Gateway
    name: lattice-gateway
    namespace: lattice-gateway
    sectionName: http-listener
  rules:
  - backendRefs:
    - name: carts
      kind: Service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.aws/v1alpha1
kind: TargetGroupPolicy
metadata:
  name: carts-tg-policy
  namespace: carts
spec:
  targetGroupRef:
    service:
      name: carts
      port: 80
  healthCheck:
    enabled: true
    protocol: HTTP
    port: "8080"  # Note: Port is specified as a string
    path: "/actuator/health/liveness"
    intervalSeconds: 30
    timeoutSeconds: 5
    healthyThresholdCount: 5
    unhealthyThresholdCount: 2
    successCodes: "200"


