apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: carts-route
  namespace: carts
spec:
  parentRefs:
  - name: carts-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /carts
    backendRefs:
    - name: carts
      port: 80