apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: carts
  namespace: carts
spec:
  hostnames:
  - carts.myorg.com
  parentRefs:
  - kind: Gateway
    name: lattice-gateway
    namespace: lattice-gateway
    sectionName: http-listener
  rules:
  - backendRefs:
    - name: carts
      kind: Service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: vpc.lattice.aws/v1beta2
kind: TargetGroupPolicy
metadata:
  name: carts-tg-policy
  namespace: carts
spec:
  targetRef:
    group: ""
    kind: Service
    name: carts
  targetGroup:
    healthCheck:
      enabled: true
      protocol: HTTP
      port: 8080
      path: /actuator/health/liveness
      intervalSeconds: 30
      timeoutSeconds: 5
      healthyThresholdCount: 5
      unhealthyThresholdCount: 2

