apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: carts
  namespace: carts
  annotations:
    application-networking.k8s.aws/healthcheck-port: "8080"
    application-networking.k8s.aws/healthcheck-protocol: "HTTP"
    application-networking.k8s.aws/healthcheck-path: "/actuator/health/liveness"
    application-networking.k8s.aws/healthcheck-interval: "30"
    application-networking.k8s.aws/healthcheck-timeout: "5"
    application-networking.k8s.aws/healthcheck-healthy-threshold: "5"
    application-networking.k8s.aws/healthcheck-unhealthy-threshold: "2"
    application-networking.k8s.aws/success-codes: "200"
spec:
  hostnames:
  - carts.myorg.com
  parentRefs:
  - kind: Gateway
    name: lattice-gateway
    namespace: lattice-gateway
    sectionName: http-listener
  rules:
  - backendRefs:
    - name: carts
      kind: Service
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
