apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gateway.yaml
- httproute.yaml
- service-network.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: carts
      namespace: carts
      annotations:
        networking.amazonaws.com/vpc-lattice-service: "true"
  target:
    kind: Service
    name: carts
    namespace: carts
